### ISSUE TITLE
Field may not get deserialized during South data migration

### ISSUE THREAD

**Issue by yigor** [bradjasper/django-jsonfield#119]
Hello, I faced a situation when data in one field got corrupted because if was't deserialized on load.  If happens if during South data migration JSONField gets assigned before the id field. It's related to these issues: #116 and #52. In the pre_init method you check that the pk field is assigned which causes the fields's value to remain as a string. And after I save the model the {"key":"value"} JSON turns into "{\"key\":\"value\"}" string. And if you run one more migration on this model you'll get "{\\"key\\":\\"value\\"}" and so on. As I don't see the point in this check I've created a straightforward pull request addressing this issue: #118. This change solved my problem and as far as I see didn't break anything but there may be some pitfall's I'm not aware of. 
I use Django 1.6.10 and South 1.0.2.

**Comment by denisvlr** [comment]
Ran into the exact same issue, tried your branch but it created a validation error "Enter valid JSON".

**Comment by yigor** [comment]
@denisvlr during migration? Could you please provide the input that caused the crash?

**Comment by EmilStenstrom** [comment]
Using your branch solved this issue for me. We had simple model instances with JSONFields. Running a south DataMigration over those instances and changing another field (in our case just writing to a field called "title" and saving), make our jsonfield turn out with quotes around it. 

Running on @yigor s branch fixed this issue for us, so that's what we're doing for now.

Would love for @bradjasper to merge this so we can go back to using a pypi version instead of a tarball from github.

**Comment by bradjasper** [comment]
Will definitely try and get to this sooner than later. Am trying to get another set of tests added first to cover some existing problems that keep occurring.

**Comment by neerajd-impinge** [comment]
@bradjasper Still getting the same validation error when installed pypi version .

**Comment by winsento** [comment]
+1

**Comment by afausti** [comment]
The the pre_init method is causing this validation error for me. 

I am using version 1.0.3 from pypi and here is my model:

```
class Metric(models.Model):
    """Metric definition.
    """
    metric = models.CharField(max_length=16, primary_key=True,
                              help_text='Metric name')
    # some metrics may not have unit
    unit = models.CharField(max_length=16, null=True, blank=True, default='',
                            help_text='Metric unit, astropy compatible string')
    description = models.TextField(help_text='Metric description')
    operator = models.CharField(max_length=2, blank=False, default='<',
                                help_text='Operator used to test measurement value'
                                          ' against metric specification')
    # some metrics may not have associated parameters
    parameters = JSONField(null=True, blank=True, default=None,
                           help_text='Parameters used to define the metric')
    specs = JSONField(null=True, blank=True, default=None, help_text='Array of metric specification')
    reference = JSONField(null=True, blank=True, default=None, help_text='Metric reference')

    def __str__(self):
        return self.metric
```
and serializer:
```
class MetricSerializer(serializers.ModelSerializer):
    """Serializer for `models.Metric` objects.
    """
    class Meta:
        model = Metric
        fields = ('metric', 'unit', 'description', 'operator',
                  'parameters', 'specs', 'reference',)
```

**Comment by dmkoch** [comment]
Closing this issue because only Django 1.8 or greater is now supported, and South is deprecated since Django migration were add in 1.7.

Please reopen a new issue if there is a problem with Django 1.8 or greater. Thanks!
