### ISSUE TITLE
Docs: Please use "jsonfield" and not "django-jsonfield"

### ISSUE THREAD

**Issue by guettli** [bradjasper/django-jsonfield#123]
Hi,

unfortunately there are two projects called "django-jsonfield".

Since "django-jsonfield" is a different project on pypi, I suggest you use "jsonfield" to refer to your project.

Please update at least the README.

Background: I just wasted some time, just because of this confusion.

Thank you for this nice django field!

**Comment by bradjasper** [comment]
I've added a note to clear this up.
