### ISSUE TITLE
Import Warning Django 1.8

### ISSUE THREAD

**Issue by lzanuz** [bradjasper/django-jsonfield#132]
RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.

**Comment by joaoricardo000** [comment]
+1

This is the full warning output when starting a django 1.8 server:

WARNING:py.warnings:/opt/apps/virtualenvs/venv/local/lib/python2.7/site-packages/south/modelsinspector.py:20: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

**Comment by lwm** [comment]
@lzanuz @joaoricardo000 

#141 got merged. Appreciated if you could confirm this isn't here any more.

**Comment by dmkoch** [comment]
#141 should close this issue, please reopen if there is still a warning after the version following 1.0.3 is released.
