### ISSUE TITLE
NameError: global name 'basestring' is not defined [Python 3.4]

### ISSUE THREAD

**Issue by anuragxel** [bradjasper/django-jsonfield#134]
Django 1.8.1 was crashing in widgets.py because of an `isinstance()` which raised a NameError on line 12.

![screenshot from 2015-06-18 02 06 31](https://cloud.githubusercontent.com/assets/5917609/8218575/45d01456-1533-11e5-809d-2a422f1bb9aa.png)

I guess the following fixes it (putting this just below the import directives), btw

```
try:
    unicode = unicode
except NameError:
    str = str
    unicode = str
    bytes = bytes
    basestring = (str,bytes)
else:
    str = str
    unicode = unicode
    bytes = str
    basestring = basestring
```

Apologies if I haven't followed the decorum. Hope this helps.

**Comment by Gwildor** [comment]
Having this issue as well, pretty annoying. I'm on Django 1.9.2 and Python 3.5, but this is of course something which only can work on Python 2, because `basestring` doesn't exist in Python 3. I had no choice besides simply not using the widget at all.

**Comment by anuragxel** [comment]
I have commented a fix on my post. Please try that if it works for you. Just add those lines in widget.py

**Comment by dmkoch** [comment]
There are at least two projects on PyPI with similar (admittedly confusing) names:

1. https://pypi.python.org/pypi/jsonfield (This project)

2. https://pypi.python.org/pypi/django-jsonfield

This issue looks like it applies to project 2.
