### ISSUE TITLE
Problem with existing migrations, PG 9.4, and jsonb

### ISSUE THREAD

**Issue by dcramer** [bradjasper/django-jsonfield#135]
Something in a patch release broke behavior.

http://semver.org/

0.9.13 is fine, 0.9.15 is broken

https://github.com/getsentry/sentry/issues/1648

**Comment by bradjasper** [comment]
Thanks for the report. Looks like it probably should have been a breaking change. At the time it seemed like a relatively minor fix, but in hindsight it probably would have been safer to bump at least the minor version.

Not really sure how to handle this now—I've added a note to the front of the project that notes 1.0+ follows semvar more strictly. Let me know if you have any other suggestions.
