### ISSUE TITLE
JSONField is represented in Postgres 9.4 as Text

### ISSUE THREAD

**Issue by ferasodh** [bradjasper/django-jsonfield#140]
Hi,

I'm trying to use your library to get json type support in django. Here is my model:

```
class Classifier(models.Model):
     name = models.CharField(max_length=50)
     attributes = JSONField()
```

and here is database table:

```
   Column   |         Type          |                             Modifiers                              | Storage  | Stats target | Description 
------------+-----------------------+--------------------------------------------------------------------+----------+--------------+-------------
 id         | integer               | not null default nextval('classifier_classifier_id_seq'::regclass) | plain    |              | 
 name       | character varying(50) | not null                                                           | extended |              | 
 attributes | text                  | not null                                                           | extended |              | 
```

Why is attributes type is text? shouldn't it be json?

Thanks,
Feras

**Comment by jangnezda** [comment]
Hi, looks like the support for Postgres 'json' column type has been removed somewhere around version 1.0. More information here: #57
If you need this, you'll have to use 0.9.x version of jsonfield package.

**Comment by dmkoch** [comment]
If you want the underlying column type to be json (jsonb actually) and you're using PostgreSQL >= 9.4, then your best bet is to use the native JSONField included in Django >= 1.9 

https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/fields/#jsonfield

This module is still useful if you need to support JSON in databases other the Postgres or are a third party module that needs to be database agnostic.

But if you're an end user using Postgres and want full-featured JSON support, use JSONField from Django.

**Comment by xlotlu** [comment]
> This module is still useful if you need to support JSON in databases other than Postgres or are creating a third party module that needs to be database agnostic.
> 
> But if you're an end user using Postgres and want full-featured JSON support, use JSONField from Django.

This should make it into the documentation.

**Comment by dmkoch** [comment]
Good idea -- I added to the README.
