### ISSUE TITLE
Provide wheel package on PyPI

### ISSUE THREAD

**Issue by edmorley** [bradjasper/django-jsonfield#142]
Please could you provide a wheel package on PyPI alongside the standard package? http://pythonwheels.com/

Thanks :-)

**Comment by paltman** [comment]
See #150

**Comment by edmorley** [comment]
Many thanks :-)

**Comment by dmkoch** [comment]
I believe I correctly uploaded a wheel to PyPI for version 2.0.0. Please reopen the ticket if you notice a problem. Thanks!

**Comment by edmorley** [comment]
Looks great - thank you!
