### ISSUE TITLE
NameError: global name 'total_seconds' is not defined with DurationField

### ISSUE THREAD

**Issue by bijanvakili** [bradjasper/django-jsonfield#145]
When trying to encode a `DurationField`, you'll get the following exception:

```
NameError: global name 'total_seconds' is not defined
```

This is because the `encoder.py` is calling a non-existent function `total_seconds` (or perhaps a function that needs to be imported?) here:
https://github.com/bradjasper/django-jsonfield/blob/master/jsonfield/encoder.py#L41

**Comment by paltman** [comment]
This is fixed in #149

**Comment by dmkoch** [comment]
PR #149 is released as part of version 2.0.0. Thanks!
