### ISSUE TITLE
Why doesn't `JSONFieldBase` respects the `prepared` parameter?

### ISSUE THREAD

**Issue by mandx** [bradjasper/django-jsonfield#151]
The `prepared` argument is there, and from what I understand it declares if the `value` is ready to written to the database. Something like this:

``` python
def get_db_prep_value(self, value, connection, prepared=False):
    """Convert JSON object to a string"""
    if self.null and value is None:
        return None
    if not prepared:
        value = json.dumps(value, **self.dump_kwargs)
    return value
```

The current test suit (checkout from master) runs without failures with this change.

**Comment by mandx** [comment]
Some background on why I ask this:

I'm using [this package](https://github.com/mbraak/django-dumpdb) to efficiently dump/load large databases, but it doesn't work properly with `JSONField`, when the data is restored into the model, the JSON field attribute ends up with the JSON string as the value.

**Comment by dmkoch** [comment]
Let me know if PR #182 doesn't fix this. Thanks!
