### ISSUE TITLE
Django 1.10 depreciation warning

### ISSUE THREAD

**Issue by pypetey** [bradjasper/django-jsonfield#153]
RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.

**Comment by paltman** [comment]
@pypetey thanks for filing this issue. I'll see what I can do about resolving this shortly.

**Comment by mvanderlinde** [comment]
Any update on when the fix will be merged into a release? The current version on PyPI still has the DeprecationWarning.

**Comment by kevinmickey** [comment]
See PR #164

**Comment by dmkoch** [comment]
Please reopen this issue if you still have problems with version 2.0.0. Thanks!
