### ISSUE TITLE
ImportError: cannot import name util

### ISSUE THREAD

**Issue by pembo13** [bradjasper/django-jsonfield#154]
I had to update forms.py to

``` python
try:
    import json
except ImportError:  # python < 2.6
    from django.utils import simplejson as json
from django.core.exceptions import ValidationError
from django.forms import fields
```

and replace `utils.ValidationError` with `ValidationError`

**Comment by pembo13** [comment]
This affects Django 1.9

**Comment by paltman** [comment]
@pembo13 thanks for this report

**Comment by patroqueeet** [comment]
no fix yet? its a blocker for 1.9 upgrade

**Comment by SachitNayak** [comment]
yeah there is problems with this still ... will have follow @pembo13  
instructions

**Comment by patroqueeet** [comment]
@pembo13  what about a pull request?

**Comment by pembo13** [comment]
@patroqueeet do you still need a pull request? Looks like you've taken care of it already.

**Comment by patroqueeet** [comment]
it's a holy mess. after more investigation I found that the json field in my project is this one here: https://github.com/derek-schaefer/django-json-field/blob/master/json_field/forms.py and I fixed it there and it perfectly worked for me. so is this ticket totally messed up?

**Comment by dmkoch** [comment]
As @patroqueeet noted, this bug report is for a different project, closing the issue.
