### ISSUE TITLE
add include_package_data to setup.py so PIP can install cleanly - again

### ISSUE THREAD

**Issue by mattjmorrison-imt** [bradjasper/django-jsonfield#155]
It looks like this commit: https://github.com/bradjasper/django-jsonfield/commit/d731630e33a4fda442500201398f21d929d1ed16

was undone by this commit: https://github.com/bradjasper/django-jsonfield/commit/4e28494aa9047da47a2ea2789fa275c32c5062c9

Is there a reason for that, or would you accept a PR that adds the `include_package_data` flag back?

**Comment by dmkoch** [comment]
I added it back in version 2.0.1.
