### ISSUE TITLE
Remove Django entirely from install_requires

### ISSUE THREAD

**Issue by andybak** [bradjasper/django-jsonfield#157]
See: https://github.com/carljm/django-model-utils/issues/183 and https://github.com/charettes/django-admin-enhancer/issues/23

**Comment by raphendyr** [comment]
This is problem in pip, not in django-jsonfield. Pip issue about it https://github.com/pypa/pip/issues/59 . As this package can't work without django, it needs to be defined as requirement. It's really not our problem that `pip install -upgrade package` doesn't do what you expect it to do. That command has implicit recursive feature that should have been deprecated long time ago, but isn't.

You can upgrade only dkango-jsonfield following this guide https://pip.pypa.io/en/latest/user_guide/#only-if-needed-recursive-upgrade

**Comment by pradyunsg** [comment]
Just dropping in to say, you might want to track pypa/pip#3806. Once that gets merged, this problem would be resolved as pip would stop upgrading dependencies to their latest version.

**Comment by dmkoch** [comment]
I fall on the side of using `pip install --upgrade --upgrade-strategy="only-if-needed"` or using something like https://github.com/jazzband/pip-tools to manage pinned dependencies.
