### ISSUE TITLE
point release incorporating recent changes

### ISSUE THREAD

**Issue by nickpell** [bradjasper/django-jsonfield#158]
Hello,

I'd like to have access to recent changes such as https://github.com/bradjasper/django-jsonfield/pull/78 by downloading via PyPi.  Are there any plans to make a new point release?

Thanks,
Nick

**Comment by nickpell** [comment]
Wondering if there's plans to release 1.0.4 or 1.1.x+? @paltman @bradjasper

**Comment by dmkoch** [comment]
Please check out version 2.0.0 on PyPI, which should have PR #78 included.
