### ISSUE TITLE
ImportError: No module named six

### ISSUE THREAD

**Issue by RevolutionTech** [bradjasper/django-jsonfield#170]
`six` is not marked as a dependency in `setup.py`, but is used in `fields.py`.

Minor issue as generally everyone has `six`, but still- if one installs `django-jsonfield` in a fresh virtualenv, they may run into issues.

**Comment by zsoldosp** [comment]
actually django bundles six into it under `django.utils.six`. [It is there already in 1.4](https://github.com/django/django/blob/stable/1.4.x/django/utils/six.py). Maybe importing that instead of `six` in the codebase could be an alternative

**Comment by RevolutionTech** [comment]
Right, and since Django 1.4 is no longer supported this isn't really relevant anymore.
