### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by orokusaki** [bradjasper/django-jsonfield#172]
Hey @bradjasper @paltman - I noticed there were a number of commits since the last release in Feb, 2015, but none after, and no release since those commits were made. I know Django ships with `JSONField` now, but it is of course Postgres-only, so not universally useful, and not useful for quick local testing on a Mac (unless you install Postgres.app).

Do you have plans to make a new release tag / upload to PyPi?

**Comment by beruic** [comment]
I could use a release too @bradjasper

**Comment by auvipy** [comment]
+1

**Comment by lskillen** [comment]
+1

See [dj-stripe issue #395](https://github.com/kavdev/dj-stripe/issues/395) (Django Stripe library) for an example of where 2.0 is highly anticipated. :-)

**Comment by dmkoch** [comment]
I upload 2.0.0 to PyPI just now. Please report any bugs!

**Comment by beruic** [comment]
Could you add a release here on Github too? The people monitoring the atom feed for your releases page will be notified :)

**Comment by dmkoch** [comment]
Done.
