### ISSUE TITLE
text field deprecated in MS SQL Server

### ISSUE THREAD

**Issue by NBajanca** [bradjasper/django-jsonfield#175]
The next version of SQL Server will discontinue the **text** data type ([source](https://msdn.microsoft.com/pt-pt/library/ms187993.aspx)):

> IMPORTANT!  ntext, text, and image data types will be removed in a future version of SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use nvarchar(max), varchar(max), and varbinary(max) instead.

If you point me in the right direction I could make this switch and a PR.

**Comment by dmkoch** [comment]
django-jsonfield uses Django's models.TextField or models.CharField which are abstractions over the underlying database field types. I believe the best place to check on this issue is with this project: https://bitbucket.org/Manfre/django-mssql/
