### ISSUE TITLE
Impossible to save blank object {} into field through ModelForm

### ISSUE THREAD

**Issue by liquidpele** [bradjasper/django-jsonfield#74]
It gets returned as None after being saved.  I've tried every combination of blank/null on the model field.  Using django 1.5, this is the basic setup:

class Thing(models.Model):
____config = JSONField(blank=True, null=True, default={})

class ThingForm(ModelForm):
____class Meta:
________model = Thing

\> w = Thing.objects.all()[0]
\> wf = Thingform({'config': {}}, instance=w)
\> wf.errors
{}
\> w = wf.save()
\> w.config is None
True
\> 
:(

**Comment by kierun** [comment]
@rogual's solution worked for me too.

**Comment by liquidpele** [comment]
Seems like it's workable now, can't verify myself since we're not using this anymore, so just closing.
